# load stream module (Official Nginx Docker image has stream module built-in, no need to load it dynamically)
# load_module /usr/lib/nginx/modules/ngx_stream_module.so;

# nginx.conf
events {
    worker_connections 1024;
}

stream {
    upstream chat_servers {
        least_conn; # 负载均衡策略：优先分配给当前连接数最少的节点
        server chatserver1:8888 max_fails=3 fail_timeout=15s;
        server chatserver2:8889 max_fails=3 fail_timeout=15s;
    }

    server {
        listen 8000; # 统一对外的 TCP 负载均衡监听端口
        proxy_pass chat_servers;
        proxy_timeout 10m;
        proxy_connect_timeout 5s;
    }
}
